baseurl: http://shawn1251.github.io
#defaultContentLanguage = "en"
title: Shawn's Note
description: Life Record & Learning Note
theme: hugo-theme-stack
#canonifyurls = true

params:
    favicon: /favicon.png
    sidebar:
        subtitle: Life Record & Learning Note
        #emoji:  🚲
        emoji: 😊
        avatar:
            enabled: true
            local: true
            src: avatar.jpg
    
    footer:
        since: 2023
    
    article:
        math: true
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0
    
    comments:
        enabled: false

        article:
        math: true
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc
menu:
    main: []
    
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/shawn1251
          params:
              icon: icons8-github

        - identifier: linkedin
          name: Linkedin
          url: https://www.linkedin.com/in/wei-siang-shawn-hong-24ba3a264/
          params:
              icon: icons8-linkedin

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200


languageCode: en
DefaultContentLanguage: en
languages:
  zh-tw:
    languageName: '繁體中文'
  en:
    languageName: 'English'
  
